AY2425S1-CS2103T-W12-4/tp

docs/DeveloperGuide.md

Update Target User Profile, Value Proposition and User Stories in DG

---

src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/event/Name.java
src/main/java/seedu/address/model/event/Time.java
src/main/java/seedu/address/model/event/Venue.java

Add event classes

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/ReadOnlyAddressBook.java
src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/event/UniqueEventList.java
src/test/java/seedu/address/model/AddressBookTest.java

Adapt current Addressbook to support Events

---

src/main/java/seedu/address/model/event/Event.java

Change event person attribute name

---

src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/event/EventName.java
src/main/java/seedu/address/model/util/SampleDataUtil.java

Edit sample data and renamed attribute class for events

---

src/main/java/seedu/address/storage/JsonAdaptedEvent.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json

Add storage components for saving and loading Event data 

---

src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/commands/ViewContactCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/logic/parser/ViewContactCommandParser.java
src/main/java/seedu/address/model/person/NameMatchesKeywordsPredicate.java

- Add NameMatchesKeywordsPredicate for strict match
- Add abstract class ViewCommand
- Add class ViewContactCommand
- Add class ViewCommandParser to parse ViewCommand
- Add class ViewContactCommandParser to parse ViewContactCommand

Add view contact command

---

src/main/java/seedu/address/model/event/Event.java

Change event attributes to final

---

src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/storage/JsonAdaptedEvent.java

Rename mainContact to celebrity

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/logic/commands/ListPersonCommand.java
src/main/java/seedu/address/logic/commands/ViewContactCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/ListPersonCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Add List Person Command

---

src/main/java/seedu/address/logic/commands/ViewContactCommand.java
src/main/java/seedu/address/logic/commands/ViewEventCommand.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/logic/parser/ViewContactCommandParser.java
src/main/java/seedu/address/logic/parser/ViewEventCommandParser.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/event/EventNameMatchesKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java

- Add class ViewEventCommand
- Add class ViewEventCommandParser
- Add updateFilteredEventList method in ModelManager

Add view event command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/ViewEventCommand.java

Add view event message

---

src/main/java/seedu/address/logic/commands/ListEventCommand.java
src/main/java/seedu/address/logic/parser/ListCommandParser.java
src/main/java/seedu/address/model/Model.java

Add List Event Command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddEventCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedEvent.java
src/test/java/seedu/address/testutil/EventBuilder.java

Add poc list feature

---

src/main/java/seedu/address/logic/commands/FilterPersonCommand.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/logic/parser/FilterEventCommandParser.java
src/main/java/seedu/address/logic/parser/FilterPersonCommandParser.java
src/main/java/seedu/address/model/person/NameMatchesKeywordsPredicate.java
src/main/java/seedu/address/model/person/TagMatchesKeywordsPredicate.java

Add FilterPersonCommand Functionality

---

docs/UserGuide.md

Update UG Summary, FAQ, Known Issues

---

src/main/java/seedu/address/logic/commands/AddEventCommand.java
src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedEvent.java
src/test/java/seedu/address/testutil/EventBuilder.java

Change POC list to set

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/event/Time.java

Add check for start time before endtime

---

src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/ui/card/EventCard.java
src/main/resources/view/DarkTheme.css
src/main/resources/view/EventListCard.fxml

Add tag into contacts string

---

src/main/java/seedu/address/storage/JsonAdaptedEvent.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java

closes https://github.com/AY2425S1-CS2103T-W12-4/tp/issues/162

Edit deserialiser to reference same object instead of creating duplicate

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddEventCommand.java
src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/event/EventName.java
src/main/java/seedu/address/model/event/Venue.java
src/main/java/seedu/address/model/person/Name.java

Handle blank event inputs

---

src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/event/UniqueEventList.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java

Fix overlap checker for EditEvent

---

src/main/java/seedu/address/logic/commands/AddPersonCommand.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsData.json
src/test/java/seedu/address/testutil/TypicalPersons.java

Change Usage Message and TypicalPersons to reflect context

---

src/main/java/seedu/address/ui/card/EventCard.java

Add empty POC list label

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddEventCommand.java
src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/logic/parser/ParserUtil.java

Simplify event time format

---

src/main/java/seedu/address/logic/commands/AddEventCommand.java
src/main/java/seedu/address/logic/commands/EditEventCommand.java

Prevent duplicate celebrity in poc list

---

src/main/java/seedu/address/logic/commands/EditEventCommand.java

Add error handling for person not found

---

src/main/java/seedu/address/logic/commands/AddEventCommand.java
src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/storage/JsonAdaptedEvent.java

Add check for celebrity absence in contact list

---

src/main/java/seedu/address/logic/commands/EditPersonCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/event/UniqueEventList.java
src/test/java/seedu/address/logic/commands/AddPersonCommandTest.java

Fix edit person bug

---

src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/logic/commands/EditPersonCommand.java
src/main/java/seedu/address/logic/parser/AddEventCommandParser.java
src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java
src/main/java/seedu/address/logic/parser/EditEventCommandParser.java
src/main/java/seedu/address/logic/parser/EditPersonCommandParser.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AddPersonCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditPersonCommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java

Refactor edit event and person to allow deletion of optional fields

---

src/main/java/seedu/address/logic/LogicManager.java
src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/ConfirmDeleteCommand.java
src/main/java/seedu/address/logic/commands/exceptions/CommandException.java
src/main/java/seedu/address/logic/commands/exceptions/PendingCommandException.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java

Fix pending mechanism

---

src/main/java/seedu/address/logic/commands/EditEventCommand.java
src/main/java/seedu/address/logic/parser/EditEventCommandParser.java

Update editEvent to allow POC list clearing

---

docs/DeveloperGuide.md

Fix DG typos

---

docs/UserGuide.md
src/main/java/seedu/address/logic/parser/AddPersonCommandParser.java

Ug update known issue

---

src/main/java/seedu/address/model/event/Event.java
src/main/java/seedu/address/model/person/Person.java

Fix equals methods

---

src/main/java/seedu/address/model/event/Venue.java

Fix buggy output

---

docs/UserGuide.md
src/main/java/seedu/address/model/event/EventCelebrityMatchesKeywordPredicate.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/NameMatchesKeywordsPredicate.java

Fix case sensitivity bug

---

docs/DeveloperGuide.md

Remove unnecessary terms and update glossary
